### ISSUE TITLE
[Bug]: Missing migration documentation

### ISSUE THREAD

**Issue by DDavidPrime** [Iteo/theme_tailor#101]
### Desctibe the bug

Upon researching how to migrate from an older version (2.0.0) to the latest one, I wanted to check out the migration example on how to do that. Upon opening the link at the bottom of the migration section, it redirected me to a `404 - Not found` page instead of the migration example.

### Reproduction steps

1. Open theme_tailor on pub.dev and find the migration section (https://pub.dev/packages/theme_tailor#migration-from-tailor-to-tailormixin).
2. Click on the link saying `To see an example of how to migrate, head out to [example: migration_example](https://github.com/Iteo/theme_tailor/blob/main/packages/theme_tailor/example/lib/migration_from_tailor_to_tailor_mixin.dart)`

### Expected behaviour

A page to proper migration documentation should be opened.

### Dart version

Irrelevant

### Package version

2.0.0

### What platform are you seeing the problem on?

iOS, Android, Web, Windows, macOS, Linux

### Relevant log output

```shell
None
```

**Comment by Falynsky** [comment]
Migration file will be restored soon to the main, thanks for noticing 😁
