### ISSUE TITLE
[Feature]: Auto generate method to merge Themes

### ISSUE THREAD

**Issue by marcosgcd** [Iteo/theme_tailor#103]
### Problem

I am writing Widgets so that the theme defined in the ThemeExtension can be overwritten in the properties of the Widget.

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:theme_tailor_annotation/theme_tailor_annotation.dart';

part 'example.tailor.dart';

@TailorMixinComponent()
class MyButtonTheme extends ThemeExtension<MyButtonTheme>
    with DiagnosticableTreeMixin, _$MyButtonThemeTailorMixin {
  const MyButtonTheme({
    this.padding = const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
    this.color,
  });
  @override
  final EdgeInsets padding;
  @override
  final Color? color;
}

class MyButton extends StatelessWidget {
  const MyButton({super.key, required this.child, this.onPressed, this.theme});
  final Widget child;
  final void Function()? onPressed;
  final MyButtonTheme? theme;

  @override
  Widget build(BuildContext context) {
    final theme = this.theme ?? MyTheme.of(context).myButtonTheme;

    return GestureDetector(
      onTap: onPressed,
      child: Container(
        padding: theme?.padding,
        color: theme?.color,
        child: child,
      ),
    );
  }
}
```

This will work fine if the developer has not set a custom padding for `MyButton` in `MyTheme`.
```
final theme = this.theme ?? MyTheme.of(context).myButtonTheme;
```
But if he has. `this.theme` will still have the padding defined in the constructor of `MyButtonTheme` and the developer would need to explicitly pass the correct value. Or would need to read the correct value from `MyTheme.of(context).myButtonTheme` before passing it to `MyButton`

```

// MyTheme(myButtonTheme: MyButtonTheme(padding: const EdgeInsets.all(8)))


MyButton(
    onPressed: () {},
    theme: MyTheme.of(context).myButtonTheme.copyWith(
         colors: Colors.green
      ),
     child: const Text('Button'),
);
```

Having to use MyTheme.of(context).myButtonTheme.copyWith is not that nice. So I would like to handle this case in the Widget itself 

### Desired Solution

Generate `.merge` for Themes, so theme can be merged. 

```
final theme = this.theme.merge( MyTheme.of(context).myButtonTheme);
```

### Alternatives Considered

I will write the merge function myself. But It would be nice to have it autogenerated 

```
@TailorMixinComponent()
class MyButtonTheme extends ThemeExtension<MyButtonTheme>
    with DiagnosticableTreeMixin, _$MyButtonThemeTailorMixin {
  const MyButtonTheme({
    this.padding = const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
    this.color,
  });
  @override
  final EdgeInsets padding;
  @override
  final Color? color;

  MyButtonTheme merge(MyButtonTheme other) {
   // defalutTheme is used to take Properties defined in the Constructor to account
    const defaultTheme = MyButtonTheme();
    return MyButtonTheme(
      padding: padding == defaultTheme.padding ? other.padding : padding,
      color: other.color ?? color,
    );
  }
}
```

### On which platorm do you expect this solution?

All

**Comment by Falynsky** [comment]
Thank you for the suggestion, but I believe your proposition is too specific for inclusion in the generated code. 
However, the issue could potentially be addressed by making `final MyButtonTheme? theme` non-nullable and `required` in the constructor. If you wish to change a parameter in a specific instance of MyButton, you could pass a new instance of `MyButtonTheme` to `MyButton` using `.copyWith()`.

I hope this helps!

**Comment by dickermoshe** [comment]
@marcosgcd 

I really want this added.
Any theme which has a `bool merge` field should have a merge method.

Would you be open for a PR? This is a really simple fix (I already have it working on a fork)
