### ISSUE TITLE
How to add operator==, hashCode and debugFillProperties.

### ISSUE THREAD

**Issue by InAnadea** [Iteo/theme_tailor#19]
flutter 3.0.2
theme_tailor_annotation 1.0.0
theme_tailor 1.0.1

Example code:
```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:theme_tailor_annotation/theme_tailor_annotation.dart';

part 'ng_theme.tailor.dart';

@Tailor(
  themes: ['light'],
  themeGetter: ThemeGetter.onBuildContext,
)
class _$NgTheme {
  static const List<Color> test = [Colors.black];
}
```

Generated code:
```
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_element

part of 'ng_theme.dart';

// **************************************************************************
// ThemeTailorGenerator
// **************************************************************************

class NgTheme extends ThemeExtension<NgTheme> {
  NgTheme({
    required this.test,
  });

  final Color test;

  static final NgTheme light = NgTheme(
    test: _$NgTheme.test[0],
  );

  @override
  NgTheme copyWith({
    Color? test,
  }) {
    return NgTheme(
      test: test ?? this.test,
    );
  }

  @override
  NgTheme lerp(ThemeExtension<NgTheme>? other, double t) {
    if (other is! NgTheme) return this;
    return NgTheme(
      test: Color.lerp(test, other.test, t)!,
    );
  }
}

extension NgThemeBuildContext on BuildContext {
  NgTheme get ngTheme => Theme.of(this).extension<NgTheme>()!;
}

```
Expected result: 
debugFillProperties must be generated
operator == must be generated
hashCode must be generated

**Comment by Rongix** [comment]
Hello there, thanks for opening the issue. 
Both of the mentioned features are already developed and will be available in the next release (very soon);
Hash code and == operator: https://github.com/Iteo/theme_tailor/pull/18
Flutter's diagnosticable (debug fill properties): https://github.com/Iteo/theme_tailor/pull/15

**Comment by Rongix** [comment]
There is a new release with the mentioned features available. Please upgrade packages to the newest versions. There are a lot of changes, so please read the release notes and updated readme. In summary, to add support for 'debugFillProperties'; add the following import to the file:
```dart
import 'package:flutter/foundation.dart';
```
[theme_tailor_annotation 1.0.1](https://pub.dev/packages/theme_tailor)
[theme_tailor 1.0.2](https://pub.dev/packages/theme_tailor)

**Comment by InAnadea** [comment]
Thank you!
