### ISSUE TITLE
Nested theme is getting generated of dynamic type

### ISSUE THREAD

**Issue by jascodes** [Iteo/theme_tailor#44]
As you can see below `final dynamic buttonTheme;` of dynamic type is being generated.

```
// ignore_for_file: unused_element, unused_field

import 'package:client_flutter/barrel.dart';

part 'button_theme.tailor.dart';

@TailorComponent(themes: [])
class _$ButtonTheme {
  static const List<TextStyle> textStyle = [];
  static const List<Color> color = [];
  static const List<double> height = [];
}
```

```
// ignore_for_file: unused_element, unused_field

import 'package:client_flutter/barrel.dart';

part 'theme.tailor.dart';

@TailorComponent(themes: [])
class _$GluTheme {
  static const List<GluButtonTheme> buttonTheme = [];
}

```

```
class GluTheme extends ThemeExtension<GluTheme> with DiagnosticableTreeMixin {
  const GluTheme({
    required this.buttonTheme,
  });

  final dynamic buttonTheme;

  @override
  GluTheme copyWith({
    dynamic buttonTheme,
  }) {
    return GluTheme(
      buttonTheme: buttonTheme ?? this.buttonTheme,
    );
  }
```

**Comment by jascodes** [comment]
@Rongix Much appretiated.

**Comment by Rongix** [comment]
If the 'GluButtonThem' is generated by Tailor, it is required to annotate it with '@themeExtension'annotation to hint the generator that it is not yet generated

Here is a full example, maybe we could explain it a bit better in the docs; let me know if it works for you
https://github.localhost/#nesting-generated-themeextensions-modular-themes--designsystems

**Comment by jascodes** [comment]
@Rongix Thanks for replying mate. I will close this request as its working as expected. The issue was related to how I was using build_runner.

**Comment by jascodes** [comment]
@Rongix Buddy my theme class are [freezed](https://pub.dev/packages/freezed) objects and I think thats the reason sometimes it not able to pick on types.
