### ISSUE TITLE
Analyzer version

### ISSUE THREAD

**Issue by pro100andrey** [Iteo/theme_tailor#45]
Hi, 

`theme_tailor` depends on `analyzer >=3.0.0 <5.0.0`

More packages depends on `analyzer >=5.1.0 <5.2.0`.

Could you please up version for analyzer?

Thanks!

**Comment by Rongix** [comment]
Fixed by 56310baa9f41de961ff3121d2daa2bfbe9b5a0d8 
Package will be update on pub in the next week
