### ISSUE TITLE
`theme_tailor_annotation` needs update

### ISSUE THREAD

**Issue by jtdLab** [Iteo/theme_tailor#66]
@Rongix Some of the features of `theme_tailor: ^1.1.0` like const themes have updated annotations (`@Tailor(constantThemes: true)`) which are not available on pub via `theme_tailor_annotation: ^1.0.3`

**Comment by jtdLab** [comment]
Given `theme_tailor: ^1.1.0` + `theme_tailor_annotation: ^1.0.3`

When running the generator on:

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart' show ThemeExtension, Theme;
import 'package:flutter/widgets.dart';
import 'package:theme_tailor_annotation/theme_tailor_annotation.dart';

part 'my_theme.tailor.dart';

@tailor
class _$MyTheme {
  static const primary = [
    Color(0xFFFFFFFF),
    Color(0xFF222222),
  ];

  static const secondary = [
    Color(0xFF3277B4),
    Color(0xFF284D72),
  ];
}
```

i get:

```bash
[SEVERE] theme_tailor on lib/src/my_theme.dart:

FormatException: Class Tailor does not have field "requireStaticConst".
Fields: 
  - themes
  - themeGetter
  - encoders
  - hashCode
  - runtimeType
```

**Comment by Rongix** [comment]
Thank you for the report and the quick reaction. We've just pushed updated versions (v1.1.1) of both packages to the pub.dev, so it should be working as expected. Cheers!
