### ISSUE TITLE
Support customizing the className in `Theme.of(context)` calls when generating extensions

### ISSUE THREAD

**Issue by jtdLab** [Iteo/theme_tailor#83]
When using `theme_tailor` and generating `themeGetter` like for example:

```dart
// some_theme.dart
@Tailor(themeGetter: ThemeGetter.onBuildContext)
class _$SomeTheme { ... }
```

the generated code looks like:

```dart
// some_theme.tailor.dart
extension SomeThemeBuildContext on BuildContext {
  SomeTheme get someTheme =>
      Theme.of(this).extension<SomeTheme>()!;
}
```

This work well with `material` apps as they are all based on `Theme`.

Currently when using [fluent_ui](https://pub.dev/packages/fluent_ui) the generated tailor extensions do not work because
the package comes with its own [FluentTheme](https://pub.dev/documentation/fluent_ui/latest/fluent_ui/FluentTheme-class.html) and [FluentThemeData](https://pub.dev/documentation/fluent_ui/latest/fluent_ui/FluentThemeData-class.html) where `ThemeExtensions` get registered.
To make it work again the generated code had to look like:

```dart
// some_theme.tailor.dart
extension SomeThemeBuildContext on BuildContext {
  SomeTheme get someTheme =>
     FluentTheme.of(this).extension<SomeTheme>()!; // <- Replace Theme with FluentTheme
}
```

This could be solved by allowing to configure the class where the extensions are expected to be registered at.

1. Via a param in `Tailor` annotation

```dart
@Tailor(themeGetter: ThemeGetter.onBuildContext, themeClassName = 'FluentTheme')
class _$SomeTheme { ... }
```

2. Via Global builder option.
```yaml
targets:
  $default:
    builders:
      theme_tailor:
        options:
          themeClassName: FluentTheme # defaults to Theme
```

This might be useful for the future to make `theme_tailor` work with other ui libs like `macos_ui` or eventually `cupertino` if they begin to support registering theme extensions in their respective themes.

**Comment by Rongix** [comment]
Hey, thanks for the suggestion; currently generator supports generating extensions on build context and then data. Would you also like to use fluent theme data? I think it should also be supported then and it complicated the design

**Comment by jtdLab** [comment]
Yeah you are right i think both cases (data + context) should be covered.
