### ISSUE TITLE
[Feature Request]: Add `MyTheme.of(context)` style `ThemeGetters`

### ISSUE THREAD

**Issue by benthillerkus** [Iteo/theme_tailor#92]
Assuming a class `TileTheme`, this is how they'd be implemented in the generated code:

```dart
static TileTheme? maybeOf(BuildContext context) {
  return Theme.of(context).extension<TileTheme>();
}

static TileTheme of(BuildContext context) {
  return maybeOf(context)!;
}
```

**Comment by Rongix** [comment]
Hello, thanks for the suggestion. As of today in the newest version `ThemeTailor` that generates whole class is deprecated and no additional features will be added there. 
The only supported way to do it is to mix the class with  `TailorMixin` or `TailorComponent`. And add the static method to the mixed class. 

```dart
part 'title_theme.tailor.dart';

@tailorMixin
class TitleTheme extends ThemeExtension<TitleTheme> with _$TitleThemeTailorMixin {
  const TitleTheme();

  static TitleTheme? maybeOf(BuildContext context) {
    return Theme.of(context).extension<TitleTheme>();
  }

  static TitleTheme of(BuildContext context) {
    return maybeOf(context)!;
  }
}

```

That being said, it may be worked on in the future when macros are added to the language.
